services:
  mysql:
    image: mysql:8.0
    container_name: homeserver-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - homeserver-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "myuser",
          "-psecret",
        ]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: homeserver-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - homeserver-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gitea:
    image: gitea/gitea:1.19
    container_name: homeserver-gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=homeserver-mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea123
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - gitea_data:/data
    depends_on:
      - mysql
    networks:
      - homeserver-network

  ollama:
    image: ollama/ollama:latest
    container_name: homeserver-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - homeserver-network

volumes:
  mysql_data:
  gitea_data:
  ollama_data:

networks:
  homeserver-network:
    driver: bridge
