name: Release

on:
  push:
    tags: ["v*"]

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ${{ github.repository }}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## What's Changed

            * Backend image: `${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-backend:${{ github.ref_name }}`
            * Frontend image: `${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-frontend:${{ github.ref_name }}`

            ### Docker Usage
            ```bash
            # Pull the new images
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-backend:${{ github.ref_name }}
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-frontend:${{ github.ref_name }}

            # Or use with docker run
            docker run -d -p 8080:8080 ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-backend:${{ github.ref_name }}
            docker run -d -p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-frontend:${{ github.ref_name }}
            ```
