name: Java Application Startup Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: verysecret
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: myuser
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Initialize database
        run: |
          mysql -h 127.0.0.1 -u root -pverysecret < init-db.sql

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Start application in background
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/mydatabase
          SPRING_DATASOURCE_USERNAME: myuser
          SPRING_DATASOURCE_PASSWORD: secret
        run: |
          java -jar build/libs/*.jar &
          echo $! > app.pid

      - name: Wait for application to start
        run: |
          echo "Waiting for application to start..."
          for i in {1..30}; do
            if curl -f http://localhost:8080/ >/dev/null 2>&1; then
              echo "Application is running!"
              exit 0
            fi
            echo "Attempt $i: Application not ready yet..."
            sleep 2
          done
          echo "Application failed to start within 60 seconds"
          exit 1

      - name: Check application health
        run: |
          # Test that the application responds
          curl -f http://localhost:8080/ || exit 1
          echo "Application startup test passed!"

      - name: Stop application
        if: always()
        run: |
          if [ -f app.pid ]; then
            kill $(cat app.pid) || true
          fi
