name: Java Startup Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: verysecret
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: myuser
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u myuser -psecret"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Start application in background
        run: |
          ./gradlew bootRun &
          APP_PID=$!
          echo "Application started with PID: $APP_PID"

      - name: Wait for application to start
        run: |
          echo "Waiting for application to start..."
          for i in {1..30}; do
            if curl -f http://localhost:8080/actuator/health >/dev/null 2>&1; then
              echo "Application is running!"
              exit 0
            fi
            echo "Attempt $i: Application not ready yet, waiting..."
            sleep 2
          done
          echo "Application failed to start within 60 seconds"
          exit 1

      - name: Check if application is responding
        run: |
          echo "Testing application endpoints..."
          curl -f http://localhost:8080/setup || echo "Setup endpoint check failed"
          echo "Application startup test completed successfully!"
